/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cqtsoggzhwzakoacpvop"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxdHNvZ2d6aHd6YWtvYWNwdm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MTQyODEsImV4cCI6MjA3OTQ5MDI4MX0.RFMV6v-CZvW-fwhxxuSZYddaiHh5sWdeUCi9DulNlvg"